### ISSUE TITLE
first-letter is an identity when applied to result of the string() function

### ISSUE THREAD

**Issue by aiwenar** [Connexions/cnx-easybake#95]
Note that tests which include this construction (`string_set` and `unicode`), therefore either those tests are wrong, or this is in fact the correct behaviour. If the latter is true, then consider this an issue with documentation instead.

**CSS**

```css
div {
    string-set: name "value";
    content: first-letter(string(name));
}
```

**HTML**

```html
<html><div></div></html>
```

**Result**

```html
<html><div>value</div></html>
```

**Expected**

```html
<html><div>v</div></html>
```
